### ISSUE TITLE
Running initial-data on a PostgreSQL db

### ISSUE THREAD

**Issue by Iionsroar** [Iionsroar/inquizitor#22]
```sh
INFO:inquizitor.commands.initial_data:Dropping tables
INFO:inquizitor.commands.initial_data:Creating initial data
Traceback (most recent call last):
  File "C:\Users\halloween\AppData\Local\pypoetry\Cache\virtualenvs\inquizitor-VFD7jJ0f-py3.9\lib\site-packages\sqlalchemy\engine\base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\halloween\AppData\Local\pypoetry\Cache\virtualenvs\inquizitor-VFD7jJ0f-py3.9\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "id" of relation "quizstudentlink" violates not-null constraint
DETAIL:  Failing row contains (null, 2, 2).
```

**Comment by Iionsroar** [comment]
solved by removing inheritance of PkModel at QuizStudentLinkInDBBase

**Comment by ralf-t** [comment]
Enge link ng dinonwload mong postgres and pgadmin

**Comment by Iionsroar** [comment]
nawala ko na, eto ver
`postgres (PostgreSQL) 13.3`

**Comment by Iionsroar** [comment]
though no need to replicate naman, can check na lang yung code added and removed sa pr

**Comment by ralf-t** [comment]
Wdym?

I can leave this nalang as is?

Btw walang 13.3 ako madl from site

**Comment by Iionsroar** [comment]
> I can leave this nalang as is?

yep, pero kung gusto mo pa rin itry, pwede naman kahit anong version siguro ng postgres
