### ISSUE TITLE
ModuleNotFoundError: No module named 'fastapi_jwt_auth'

### ISSUE THREAD

**Issue by sonarypt** [Iionsroar/inquizitor#27]
### Problem
After `poetry install` inside my virtualenv, I got this error:
```
INFO:     Will watch for changes in these directories: ['/home/user/git/ForIssues/inquizitor']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [174517] using statreload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/lib/python3.10/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/usr/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/git/ForIssues/inquizitor/./main.py", line 1, in <module>
    from inquizitor import create_app
  File "/home/user/git/ForIssues/inquizitor/./inquizitor/__init__.py", line 4, in <module>
    from fastapi_jwt_auth import AuthJWT
ModuleNotFoundError: No module named 'fastapi_jwt_auth'
```
Even manually running `pip install fastapi-jwt-auth`, I still have the same error.

### Environment
- OS: Arch Linux (amd64)
- Python: 3.10.5

**Comment by Iionsroar** [comment]
Just to make sure, have you activated the shell before running the app?

You can also try manually installing the package with `poetry add fastapi-jwt-auth`

**Comment by sonarypt** [comment]
Ok, after I rerun `poetry install`, everything is fine now. Thank you.
